name: Docker

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
#  workflow_call:

permissions:
  contents: read

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Setup docker build
      uses: docker/setup-buildx-action@v3

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_HUB_USER }}
        password: ${{ secrets.DOCKER_HUB_PASSWORD }}

    - name: Build and push
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./Dockerfile
        push: true
#        tags: robison915/awsdeploy:${{github.ref_name}}
        tags: robison915/amzlin2:latest
